name: "Hola mundo!"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Publicar version"